version: '3'
services:
  postgres:
    container_name: todolist_postgres
    image: postgres:latest
    volumes:
      - ./init-postgres.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: password